homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - romkatv/powerlevel10k
  - teamookla/speedtest

homebrew_installed_packages:
  - bat # prettier 'cat'
  - coreutils # those that come with macOS are outdated
  - eza # prettier 'ls'
  - fd # faster 'find'
  - ffmpeg
  - fnm # node version manager
  - fzf # fuzzy finder
  - git
  - gnu-tar
  - imagemagick
  - jordanbaird-ice # menu bar manager
  - jq # json formatter & other utils
  - lazygit # git gui
  - luarocks
  - mosh
  - neofetch
  - newsboat # rss reader
  - openscad
  - ripgrep # faster grep
  - rsync
  - scroll-reverser # different scroll directions for mouse and trackpad
  - speedtest
  - tree-sitter-cli
  - yt-dlp
  - zsh

homebrew_cask_apps:
  - 1password
  - alt-tab
  - discord
  - docker
  - font-jetbrains-mono-nerd-font
  - ghostty
  - google-chrome
  - iina
  - tailscale
  - transmission
  - visual-studio-code
  - zen

mas_installed_apps:
  - { id: 1438243180, name: "Dark Reader for Safari (1.4.6)" }
  - { id: 1440147259, name: "AdGuard for Safari (1.11.14)" }
  - { id: 1480933944, name: "Vimari (2.1.1)" }
  - { id: 1569813296, name: "1Password for Safari (2.15.1)" }
  - { id: 409183694, name: " Keynote (13.2)" }
  - { id: 409201541, name: " Pages (13.2)" }
  - { id: 497799835, name: " Xcode (14.3.1)" }

apt_installed_packages:
  - curl
  - fd-find
  - ffmpeg
  - git
  - imagemagick
  - iputils-ping
  - jq
  - mosh
  - newsboat
  - python3-pip
  - python3-venv
  - ripgrep
  - rsync
  - ssh
  - sudo
  - unzip
  - wget
  - zsh
